import { Modes } from "@rian8337/osu-base";
import { DifficultyHitObject } from "./DifficultyHitObject";

/**
 * Represents an osu!standard hit object with difficulty calculation values.
 */
export class OsuDifficultyHitObject extends DifficultyHitObject {
    /**
     * The speed strain generated by the hitobject.
     */
    speedStrain: number = 0;

    /**
     * The flashlight strain generated by this hitobject.
     */
    flashlightStrain: number = 0;

    private readonly radiusBuffThreshold = 30;

    protected override readonly mode = Modes.osu;
    protected override get scalingFactor() {
        const radius = this.object.getRadius(this.mode);

        // We will scale distances by this factor, so we can assume a uniform CircleSize among beatmaps.
        let scalingFactor = this.normalizedRadius / radius;

        // High circle size (small CS) bonus
        if (radius < this.radiusBuffThreshold) {
            scalingFactor *=
                1 + Math.min(this.radiusBuffThreshold - radius, 5) / 50;
        }

        return scalingFactor;
    }

    override with(
        hitObjects: readonly DifficultyHitObject[],
    ): OsuDifficultyHitObject {
        const difficultyObject = new OsuDifficultyHitObject(
            this.object,
            this.lastObject,
            this.lastLastObject,
            hitObjects,
            hitObjects.length - 1,
            this.clockRate,
            this.timePreempt,
            this.isForceAR,
        );

        difficultyObject.angle = this.angle;
        difficultyObject.lazyJumpDistance = this.lazyJumpDistance;
        difficultyObject.minimumJumpDistance = this.minimumJumpDistance;
        difficultyObject.minimumJumpTime = this.minimumJumpTime;
        difficultyObject.travelDistance = this.travelDistance;
        difficultyObject.travelTime = this.travelTime;

        return difficultyObject;
    }
}
