import { Modes } from "@rian8337/osu-base";
import { DifficultyHitObject } from "./DifficultyHitObject";

/**
 * Represents an osu!standard hit object with difficulty calculation values.
 */
export class OsuDifficultyHitObject extends DifficultyHitObject {
    /**
     * The speed strain generated by the hitobject.
     */
    speedStrain = 0;

    override get smallCircleBonus(): number {
        return Math.max(1, 1 + (30 - this.object.radius) / 40);
    }

    protected override readonly mode = Modes.osu;
}
