name: Publish to GitHub Pages
on:
  release:
    types:
      - released
env:
  docVersion_PATH: /
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Update version path
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo docVersion_PATH=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2)/ >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install main dependencies
        run: npm i

      - name: Lerna bootstrap
        run: lerna bootstrap

      - name: Build website # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm run generate-docs-linux

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          target-folder: ${{ env.docVersion_PATH }}
          clean: true
          clean-exclude: '["version"]'